// Auto-generated by R3 mock data pipeline
// -------------------------------------------------------------
// Configuration assumptions used by recommendation engine.
// All thresholds documented with literature source.
// Editable via Admin > Assumptions tab.
// Config state persists in localStorage per state selection.

export interface AssumptionEntry {
  key: string;
  category: string;
  description: string;
  default_value: number | string | object;
  current_value: number | string | object;
  source: string;
  editable: boolean;
}

export const CONFIG_ASSUMPTIONS = {"fogging_cadence":{"high_risk_days":7,"moderate_risk_days":14,"low_risk_days":30,"source":"NVBDCP Odisha Activity Matrix by Risk Tier","editable":true},"fogging_overdue_threshold":{"high_risk_days_past_target":3,"moderate_risk_days_past_target":4,"low_risk_days_past_target":15,"source":"NVBDCP operational tolerance guidance","editable":true},"vector_index_outbreak":{"bi_threshold":5,"hi_threshold_pct":4,"ci_threshold_pct":3,"source":"WHO Dengue Guidelines 2009 / NVBDCP Circular","editable":true},"coverage_tiers":{"high_threshold_pct":75,"medium_threshold_pct":40,"low_threshold_pct":0,"source":"PRISM-H internal standard aligned with NVBDCP household survey targets","editable":true},"recommendation_priority":{"urgent_conditions":["high_risk AND fogging_overdue","high_risk AND major_breeding_sites_open >= 3","high_risk AND bi > outbreak_threshold AND survey_gap"],"routine_conditions":["moderate_risk AND scheduled activities on track","low_risk AND no anomaly"],"source":"Adapted from NVBDCP Odisha Activity Matrix by Risk Tier","editable":true}} as const;

// Recommendation rules — derived from NVBDCP Odisha Activity Matrix
// Each rule: [condition, action_text, priority, protocol_reference]
export const RECOMMENDATION_RULES = [
  {
    condition: "forecast_risk === 'high' && fogging_status === 'overdue'",
    action_text: "Schedule cold fogging within 48hrs",
    priority: "urgent",
    protocol_reference: "NVBDCP: high-risk hotspot, weekly fogging protocol",
  },
  {
    condition: "forecast_risk === 'high' && major_open >= 3",
    action_text: "Deploy source reduction team",
    priority: "urgent",
    protocol_reference: "NVBDCP: high-risk, intensive weekly source reduction drives",
  },
  {
    condition: "forecast_risk === 'high' && bi > 5",
    action_text: "Anti-larval measures + fogging",
    priority: "urgent",
    protocol_reference: "WHO: BI > 5 = outbreak risk. NVBDCP: weekly temephos/larvicides",
  },
  {
    condition: "forecast_risk === 'high' && coverage_tier === 'low'",
    action_text: "Deploy survey teams",
    priority: "urgent",
    protocol_reference: "NVBDCP: high-risk hotspot requires weekly larval surveillance",
  },
  {
    condition: "forecast_risk === 'moderate' && fogging_status === 'overdue'",
    action_text: "Schedule fogging this week",
    priority: "routine",
    protocol_reference: "NVBDCP: moderate risk, fortnightly cluster-based fogging",
  },
  {
    condition: "forecast_risk === 'moderate' && major_open >= 2",
    action_text: "Conduct source reduction visit",
    priority: "routine",
    protocol_reference: "NVBDCP: moderate risk, fortnightly source reduction drives",
  },
  {
    condition: "forecast_risk === 'moderate' && coverage_tier === 'low'",
    action_text: "Increase larval surveillance to fortnightly",
    priority: "routine",
    protocol_reference: "NVBDCP: moderate risk, fortnightly surveillance protocol",
  },
  {
    condition: "forecast_risk === 'low' && any_outbreak_threshold_breached",
    action_text: "Investigate anomaly + re-verify indices",
    priority: "routine",
    protocol_reference: "NVBDCP: low-risk anomaly warrants inspection escalation",
  },
  {
    condition: "forecast_risk === 'high'",
    action_text: "Maintain weekly cadence — no gaps detected",
    priority: "routine",
    protocol_reference: "NVBDCP: high-risk wards require sustained weekly protocols even when metrics stable",
  },
  {
    condition: "default",
    action_text: "Continue routine monitoring",
    priority: "routine",
    protocol_reference: "NVBDCP standard monitoring cadence for area risk tier",
  },
];
