import { getFilteredRegions, getMonthlyTimeSeries, getWeeklyTimeSeries, getOutbreakPredictions, getFilteredHotspots, getWeatherObserved, getHotspotAlerts, getNewsAlerts, getLineListing, getFilteredKpi, setActiveState, getDefaultHistoricalDateRange } from "./data/mockData";
setActiveState("karnataka");
const dates = getDefaultHistoricalDateRange();
console.log("Default dates:", dates);
const f = { state: "Karnataka", district: "All Districts", block: "All Blocks", disease: "Dengue", ...dates } as any;
console.log("\n=== State-wide Karnataka ===");
console.log("KPI:", getFilteredKpi(f));
const r = getFilteredRegions(f);
console.log("Districts:", r.length, r.map(x => `${x.name}=${x.confirmed}`));
console.log("Predictions:", getOutbreakPredictions(f).length);
console.log("Weekly TS first/last:", getWeeklyTimeSeries(f)[0], getWeeklyTimeSeries(f).slice(-1)[0]);
console.log("LineListing:", getLineListing(f).length);
