import { getFilteredRegions, getMonthlyTimeSeries, getWeeklyTimeSeries, getOutbreakPredictions, getFilteredHotspots, getWeatherObserved, getHotspotAlerts, getNewsAlerts, getLineListing, getFilteredKpi } from "./data/mockData";
import { setActiveState } from "./data/mockData";
setActiveState("karnataka");
const f = { state: "Karnataka", district: "Bengaluru Urban", block: "All Blocks", disease: "Dengue", timeRange: "Last 6 Months" } as any;
console.log("KPI:", getFilteredKpi(f));
const r = getFilteredRegions(f);
console.log("Regions count:", r.length);
console.log(r.map(x => `${x.name}/${x.type}=conf:${x.confirmed}`).join("\n"));
console.log("Weekly TS:", getWeeklyTimeSeries(f).length, "Monthly:", getMonthlyTimeSeries(f).length);
console.log("monthly sample:", getMonthlyTimeSeries(f).slice(0,3));
console.log("Predictions:", getOutbreakPredictions(f).length);
console.log("Hotspots4w:", getFilteredHotspots(f, 4).length);
console.log("Weather obs:", getWeatherObserved(f).length);
console.log("HotspotAlerts:", getHotspotAlerts(f).length);
console.log("LineListing:", getLineListing(f).length);

console.log("\n--- Weekly TS values ---");
console.log(getWeeklyTimeSeries(f).map(p => `${p.week}/${p.date}: pos=${p.positive} samples=${p.samples}`).join("\n"));
console.log("\n--- All monthly ---");
console.log(getMonthlyTimeSeries(f));
console.log("\n--- Weather obs ---");
console.log(getWeatherObserved(f).slice(0,3));
console.log("\n--- Predictions sample ---");
console.log(getOutbreakPredictions(f).slice(0,3));
console.log("\n--- Hotspots sample ---");
console.log(getFilteredHotspots(f, 4).slice(0,3));
console.log("\n--- HotspotAlerts ---");
console.log(getHotspotAlerts(f));
console.log("\n--- News ---");
console.log(getNewsAlerts(f));
