import { getFilteredRegions, getMonthlyTimeSeries, getWeeklyTimeSeries, getOutbreakPredictions, getFilteredHotspots, getWeatherObserved, getHotspotAlerts, getLineListing, getFilteredKpi, setActiveState, getDefaultHistoricalDateRange } from "./data/mockData";
setActiveState("karnataka");
const dates = getDefaultHistoricalDateRange();
const f = { state: "Karnataka", district: "Bengaluru Urban", block: "All Blocks", disease: "Dengue", ...dates } as any;
console.log("Date range:", dates);
console.log("KPI:", getFilteredKpi(f));
const r = getFilteredRegions(f);
console.log("Sub-areas:", r.length, r.map(x => `${x.name}/${x.type}=${x.confirmed}`));
console.log("Monthly TS:", getMonthlyTimeSeries(f).length, "points");
console.log(getMonthlyTimeSeries(f));
console.log("Weekly TS count:", getWeeklyTimeSeries(f).length);
console.log("Predictions:", getOutbreakPredictions(f).length);
console.log("Hotspots:", getFilteredHotspots(f, 4).length);
console.log("LineListing:", getLineListing(f).length);
